// Generated by https://quicktype.io

class Especies{
  
  List<Especie> items = new List();

  Especies();

  Especies.fromJsonList( List<dynamic> jsonList  ) {

    if ( jsonList == null ) return;
    for ( var item in jsonList  ) {
      final especie = new Especie.fromJsonMap(item);
      items.add( especie);
    }
  }
}


class Especie {
  int id;
  String especie;
  String urlimagen;
  

  Especie({
    this.id,
    this.especie,
    this.urlimagen,
    
  });

  Especie.fromJsonMap( Map<String, dynamic> json ) {

    id              = json['id'];
    especie         = json['especie'];
    urlimagen       = json['url_imagen'];

  }

  getImg() {
    return 'http://192.168.1.8:8000$urlimagen';
  }
}

